sudo: required

scala:
  - "2.11.11"

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      language: scala
      before_install:
        - sudo apt-get -qq update
        - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.7 main' >> /etc/apt/sources.list"
        - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list"
        - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
        - sudo apt-get -qq update
        - |
          sudo apt-get install -y \
            clang++-3.7 \
            llvm-3.7 \
            llvm-3.7-dev \
            llvm-3.7-runtime \
            llvm-3.7-tool \
            libgc-dev \
            libunwind7-dev

        # Install re2
        # (libre2-dev) since Xenial (16.04 LTS) http://packages.ubuntu.com/xenial/libre2-dev
        - sudo apt-get install -y make
        - export CXX=clang++-3.7
        - git clone https://code.googlesource.com/re2
        - pushd re2
        - git checkout 2017-03-01
        - make -j4 test
        - sudo make install prefix=/usr
        - make testinstall prefix=/usr
        - popd

    - os: osx
      osx_image: xcode7.3
      before_install:
        - brew update
        - brew install sbt
        - brew install bdw-gc
        - brew link bdw-gc
        - brew install jq
        - brew install re2

before_script:
  - sudo chmod +x /usr/local/bin/sbt
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] ; then
      echo "Incoming pull request from https://github.com/$TRAVIS_REPO_SLUG/pull/$TRAVIS_PULL_REQUEST";
      author=$(curl -u dummy4dummy:dummy2dummy -s "https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST" | jq -r ".user.login");
      if [ $? -ne 0 ] ; then exit 1; fi;
      echo "Pull request submitted by $author";
      signed=$(curl -s https://www.lightbend.com/contribute/cla/scala/check/$author | jq -r ".signed");
      if [ $? -ne 0 ] ; then exit 1; fi;
      if [ "$signed" = "true" ] ; then
        echo "CLA check for $author successful";
      else
        echo "CLA check for $author failed";
        echo "Please sign the Scala CLA to contribute to Scala Native";
        echo "Go to https://www.lightbend.com/contribute/cla/scala and then resubmit this pull request";
        exit 1;
      fi;
    fi;

script:
  - java -version
  - bin/scalafmt --test && sbt sbt-crossproject-test/scripted "++ 2.12.3" 'set sbtVersion in Global := "1.0.0-RC3"' sbt-crossproject-test/scripted

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
